name: "Hello world workflow"

# events
on:
  push:
    branches:
      - main
      - production


# jobs 
# jobs name
# runs-on what type of enviornment it run
# steps
# steps name
# what run

jobs:
  hello_world:
    runs-on: ubuntu-lastest
    steps:
      - name: "Print hello world"
      - run: ech0 "Hello world"