name: "First CI/CD pipeline written by me"

on: [push]


jobs:
  first_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - name: "run code"
        run: echo "Hello Abhik"

      - name: "new commit"
        run: date



