name: "Multi Event CI/Cd By Abhik"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  on_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "run code"
        run: echo "Hello Abhik,push request"
      - name: "new commit"
        run: date

  on_pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "run code"
        run: echo "Hello Abhik,Pull request"
      - name: "new commit"
        run: date

  on_workflow_dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Run code
      run: echo "Hello Abhik, workflow_dispatch triggered"

    - name: Show date
      run: date
