name: "Multi Event CI/Cd By Abhik" #name  of the pipeline

on:   #this is event trigger of the pipeline
  push:
    branches: [main]
  schedule:
    - cron: "*/5 * * * *" #every day
  pull_request:
    branches: [main]
    types: [opened, closed] #event_actions

  workflow_dispatch: #this is for manual trigger

jobs:
  on_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "run code"
        run: echo "Hello Abhik,push request"
      - name: "new commit"
        run: date

  on_pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "run code"
        run: echo "Hello Abhik,Pull request"
      - name: "new commit"
        run: date
  
  on_pull_request_closed:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: "run code"
        run: echo "Hello Abhik,Pull request opened"
      - name: "new commit"
        run: date

  on_workflow_dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: Run code
      run: echo "Hello Abhik, workflow_dispatch triggered"

    - name: Show date
      run: date
  on_schedule:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: "run code"
        run: echo "Hello Abhik,schedule request"
      - name: "new commit"
        run: date